### ISSUE TITLE
how to actually import sdk?

### ISSUE THREAD

**Issue by kanekikun420** [AlvyPiper/MoreGreenTea#1]
Hey, do i have to go all files one by one to implement all files of SDK? it looks like this http://puu.sh/kkfCZ/96fd258dc4.png

**Comment by AlvyPiper** [comment]
Is your project set to release? If not, set it to release.

**Comment by kanekikun420** [comment]
Sdk is included, now it says
Severity    Code    Description Project File    Line
Error   LNK1104 cannot open file 'tier0.lib'    GreenTea    C:\Users\Admin\Documents\Visual Studio 2015\Projects\MoreGreenTea-master\GreenTea\LINK  1

sorry for such dumb questions, i want to learn a bit from your source

**Comment by AlvyPiper** [comment]
Not a problem, also, what you posted IS a problem (hehe, sorry...) and you can get the required libraries from https://www.sendspace.com/file/2skg5g
Place them at \hl2sdk-csgo\lib and then rebuild, this happens because GitHub's desktop application continues to break and won't push things like that, it seems that was the only folder it refused to push though.

**Comment by kanekikun420** [comment]
I had to find the directory in Properties->VC++ Directories->Library directories
seems to build succesfully! Thanks really much for the source! i can learn things now.
Do you plan commenting a bit more/adding more features ? Im really interested into it and i want to learn more badly

**Comment by AlvyPiper** [comment]
Sure, I might as well add some more stuff in my free time to teach people, I will continue commenting it as I did, make sure to keep your fork of my repository updated in case you make any changes, use GitHub's application to merge and pull from the repo whenever you need. I'll close this for now, feel free to open another request if you have any problems.

**Comment by HenkieHanker2** [comment]
sendspace link stopped working ;/

**Comment by AlvyPiper** [comment]
Hi Henkie,

Please take a look at my other project, it is easier for beginners to build and use. It is located here https://github.com/AlvyPiper/Velvet

Thanks,
Alvy P
